# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gems',
            fields=[
                ('gems_id', models.AutoField(primary_key=True, serialize=False)),
                ('gems_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gems_description', models.CharField(blank=True, max_length=255, null=True)),
                ('gems_canPurchase', models.BooleanField(default=False)),
                ('gems_soldOut', models.BooleanField(default=False)),
                ('gems_images', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('reviews_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=800)),
                ('author', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='gems',
            name='gems_reviews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemstore.reviews'),
        ),
    ]
