# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gemImgs',
            fields=[
                ('gemImg_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(default='image_not_avail.png', max_length=2000)),
            ],
        ),
        migrations.RenameField(
            model_name='gems',
            old_name='gems_canPurchase',
            new_name='canPurchase',
        ),
        migrations.RenameField(
            model_name='gems',
            old_name='gems_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='gems',
            old_name='gems_soldOut',
            new_name='soldOut',
        ),
        migrations.RemoveField(
            model_name='gems',
            name='gems_images',
        ),
        migrations.RemoveField(
            model_name='gems',
            name='gems_price',
        ),
        migrations.RemoveField(
            model_name='gems',
            name='gems_reviews',
        ),
        migrations.AddField(
            model_name='gems',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='gems',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gemstore.reviews'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='author',
            field=models.CharField(default='george@internet.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='body',
            field=models.CharField(default='...', max_length=800),
        ),
        migrations.AddField(
            model_name='gems',
            name='images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gemstore.gemImgs'),
            preserve_default=False,
        ),
    ]
