# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemstore', '0002_auto_20160208_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='stars',
            field=models.SmallIntegerField(default=1),
        ),
    ]
